### ISSUE TITLE
Support play/pause state

### ISSUE THREAD

**Issue by Villhellm** [ctalkington/python-rokuecp#16]
Right now the HA integration does not track whether an app is actively playing or paused. However the ECP API does offer this information in the [media-player query](https://developer.roku.com/en-ca/docs/developer-program/debugging/external-control-api.md#querymedia-player-example)

It looks like [rokuecp.py stores this information](https://github.com/ctalkington/python-rokuecp/blob/master/rokuecp/rokuecp.py#L244), but I can't find anywhere that it is actually used 
If we pull out the `state` attribute from the `player` element we can actually implement play/pause support instead of just a toggle with the remote `play` command. 

From my tests the only two states this attribute can be are "play" and "paused" when an app is launched, or "close" when there is no active media player. I can provide help with any tests that are required, but my python skills are very limited.

**Comment by ctalkington** [comment]
someone had brought up similiar so i did recently build out media state parsing from that endpoint. It just hasnt made it to a release yet.

Roku ECP only supports "play" command as it doesnt have discrete "pause" command.

**Comment by Villhellm** [comment]
Okay, cool.

I know there is only the "play" command, but if paired with some logic tracking the play/pause state you could ignore a "pause" command if the state is already paused (or just send the "play" command to pause if it is not) and vice versa for play. I can do a PR with the logic if I'm not explaining it adequately once I see how the data can be used

**Comment by ctalkington** [comment]
MediaState would be available within self.device.media if a function was within rokuecp.py

https://github.com/ctalkington/python-rokuecp/blob/master/rokuecp/models.py#L121

**Comment by Villhellm** [comment]
So for HA pause service it could be as simple as
```python
    async def async_media_play_pause(self) -> None:
        """Send play/pause command."""
        if self.state != STATE_STANDBY and not self.device.media.paused:
            await self.coordinator.roku.remote("play")
```

if I'm not messing up my python syntax (which I probably am)

**Comment by Villhellm** [comment]
And just a quick note it seems like that class is checking for "pause" instead of "paused". I'm not sure if it is the same for all devices, but on my tv it returns "paused"

**Comment by ctalkington** [comment]
Do you have a newer or older device? Im curious if its the device type that causes such diferrences or if its outdated/no updates available.

**Comment by ctalkington** [comment]
Also, id say paused would become a state check and youd just check state in standby or paused

**Comment by ctalkington** [comment]
The bigger issue and why i havent released this mediastate yet is the increase in http calls. I really wanted to keep it to a minimum. We already have devicd info (including power state), current app, current tv channel (if roku tv and watching tuner). If we have media state that means 3  requests per update and if you have TV thats potentially 4. Our update window is about 20s apart but id like to reduce update window which would increase further. I'm not sure how much the API can take in terms of requests per minute

I did notice that the mediaplayer endpoint does expose current app though in less detail.

**Comment by Villhellm** [comment]
Ah yeah good point, it would be a state check.

I have a Hitachi 50R8, not sure how old/new that is relative to what you're thinking. I've had it for about 3 years now.

I did notice the current app info in the mediastate, but I'm not sure what would be lost if you were to remove the other request.

**Comment by Villhellm** [comment]
For what it's worth my tests show the API holding up very well to rapid requests, but I imagine that would vary device to device.
